/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tel_labs.ex2;

import java.util.List;
import java.util.Map;

import com.tel_labs.ex2.entity.Plan;
import com.tel_labs.ex2.response.PriceOutput;
import com.tel_labs.ex2.service.PlanService;
import com.tel_labs.ex2.utils.DataGenerator;

public class App {
    public static void main(String[] args) {
        try {
            DataGenerator generator = new DataGenerator();
            Map<String, Plan> planFeatureMap = generator.generatePlanFeatureMap(args[0]);
            List<String> requiredFeatures = generator.generateRequiredFeatureList(args[1]);

//            Map<String, Plan> planFeatureMap = generator.generatePlanFeatureMap("/home/didula/workspace_dlak/telepathy/tel_labs/example_2/Example1.txt");
//            List<String> requiredFeatures = generator.generateRequiredFeatureList("F4,F7,F9,F6,F5,F8,F1,F3,F0");

//            Map<String, Plan> planFeatureMap = generator.generatePlanFeatureMap("/home/didula/workspace_dlak/telepathy/tel_labs/example_2/Example2.txt");
//            List<String> requiredFeatures = generator.generateRequiredFeatureList("email,voice,admin");

            PlanService service = new PlanService();
            PlanService.setPlanFeatureMap(planFeatureMap);
            PriceOutput output = service.generateOutput(requiredFeatures);

            String outputStr = Integer.toString(output.getPrice());
            if (output.getPlans().length > 0) {
                for (String plan : output.getPlans()) {
                    outputStr += "," + plan;
                }
            }
            System.out.println(outputStr);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
